# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flowstate
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Design better user flows by analyzing recognized products. Flowstate is a library of walkthrough teardowns & design patterns from the digital products all around us. Explore trends and gain insights from the industry as a whole.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://flowstate.rehanbutt.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

plugins: [jekyll-sitemap]

collections:
  workflows:
    output: true
    permalink: /workflow/:path